#!/bin/bash -ex

# enable ip forwarding
sed -i "/^#net.ipv4.ip_forward=1/ s/#//" /etc/sysctl.conf

# change webshell and webmin listening ports in stunnel4
sed -i "s|^accept  = 12320|accept  = 22320|" /etc/stunnel/stunnel.conf
sed -i "s|^accept  = 12321|accept  = 22321|" /etc/stunnel/stunnel.conf

# configure apt-cacher-ng to bind to natbr0
CONF=/etc/apt-cacher-ng/acng.conf
sed -i "s|MainInterface|MainInterface\nBindAddress: 192.168.121.1|" $CONF

