#!/bin/bash -e
# configure cgroup in /etc/fstab and mount

# exit if already added
grep -qs /sys/fs/cgroup /etc/fstab && exit 2

echo "none /sys/fs/cgroup cgroup defaults 0 0" >> /etc/fstab
mount /sys/fs/cgroup

