#!/bin/bash

iptables_add() {
    args=$@
    if ! iptables -C $args >/dev/null 2>&1; then iptables -A $args; fi
}

#Creating default policies
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP # we're not a router

if [ "$IFACE" = "lo" ]; then
    # Allow traffic on loopback
    iptables_add INPUT -i lo -j ACCEPT
    iptables_add OUTPUT -o lo -j ACCEPT
    # Allow established connections to continue
    iptables_add INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables_add OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables_add FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
fi

if [ "$IFACE" = "br0" ]; then
    # Allow inbound connections
    iptables_add INPUT -p tcp --dport 22 -j ACCEPT #SSH
    iptables_add INPUT -p tcp --dport 53 -j ACCEPT #DNS
    iptables_add INPUT -p tcp --dport 80 -j ACCEPT #HTTP
    iptables_add INPUT -p tcp --dport 443 -j ACCEPT #HTTPS
    iptables_add INPUT -p UDP --dport 67:68 -j ACCEPT #DHCP
    iptables_add INPUT -p udp --dport 53 -j ACCEPT #DNS
    iptables_add INPUT -p tcp --dport 12320 -j ACCEPT #HTTPS
    iptables_add INPUT -p tcp --dport 12321 -j ACCEPT #HTTPS
    iptables_add INPUT -p tcp --dport 12322 -j ACCEPT #HTTPS

    iptables_add POSTROUTING -t nat -o br0 -j MASQUERADE
fi

if [ "$IFACE" = "natbr0" ]; then
    CIDR=192.168.121.0/24
    iptables_add INPUT -s $CIDR -i natbr0 -j ACCEPT
    iptables_add OUTPUT -d $CIDR -o natbr0 -j ACCEPT
    iptables_add FORWARD -i natbr0 -s $CIDR -j ACCEPT
    iptables_add POSTROUTING -t nat -s $CIDR ! -o natbr0 -j MASQUERADE
    iptables_add POSTROUTING -t mangle -p udp --dport bootpc -s $CIDR -j CHECKSUM --checksum-fill
fi

